### ISSUE TITLE
Nice to have: ability to unpublish Campaigns

### ISSUE THREAD

**Issue by rawbbit** [silverstripe/silverstripe-campaign-admin#143]
It would be nice if you could unpublish Campaigns (its contents, from the Campaign admin). For example, we're beginning to use these (with at least one client) and in some cases the campaign content has a finite lifetime.

**Comment by ScopeyNZ** [comment]
Nice idea. This will probably be powered off some sort of `unpublish` API on `ChangeSet` in silverstripe-versioned. If you feel like contributing PRs we'll be happy to review 😄

**Comment by chillu** [comment]
@silverstripeux How do you feel about this? In my view, the impacts of unpublishing are hard to communicate. It'll be misinterpreted as "revert changes". But it'll also unpublish any changes made *after* this campaign was originally published. In case you've added new child pages, and the parent page happened to be in the campaign, it'll also make this new child page inaccessible. It just sounds pretty messy overall.

**Comment by clarkepaul** [comment]
I was trying to avoid this until we get a few other features in there like Scheduled publishing and unpublishing individual items within a campaign. I think it's probably better to think about this issue more as a bulk action of the content within the campaign rather than unpublishing the actual campaign. So in that case, I think there will be times you'll want some of the items in the campaign to be unpublished and other items left as they were. It fits into the same bucket as Expiry where some content might be better being unpublished and other content should probably be archived directly, otherwise, the tree (and content states) will get really messy in the site with what needs to be published and what needs to be archived (typically DRAFT, MODIFIED means this content needs to go live at some stage, and not archived). 

I think there are too many edge cases still. Before providing the option to unpublish a campaign we would need to:
- make it super obvious that what you are about to do is dangerous, providing some examples of how things can go wrong.
- provide them with a preview of the site of what it will look like if they unpublished the campaign (future preview of site states across multiple campaigns is already an idea).
- to avoid messy sites provide an option to unpublish the campaign or unpublish and archive the content in the campaign.
- instead of allowing the whole campaign to be unpublished, provide them with the option to select all of the campaign items to be unpublished, so they can then individually uncheck items they might want to keep.
- advise if some of the items in the campaign are being used outside of the campaign and might be affected. e.g. unpublishing a file which is used both in the campaign and outside the campaign

Note: unpublishing a page unpublishes all the child pages as well (although this isn't a good experience in its self, it will make unpublishing campaigns super dangerous).

**Comment by rawbbit** [comment]
I hope I haven't opened a can of worms here! As I mentioned in the title, this was very much a 'nice-to-have' idea as it had application with at least one client project. I can appreciate this could be a risky button if added to the CMS, but as clarkepaul mentions, "make it super obvious that what you are about to do is dangerous...". It could - in theory - be solved with a good UI. 

Perhaps something to put on the back-burner for another date; bigger fish to fry. Just an idea, as I mentioned.

And to be clear: I'm not an active webdev here at Webbuilders, so I wouldn't be able to do a PR / help contribute to anything other than the discussion at this time :)

**Comment by chillu** [comment]
Yeah, I'm closing this because I don't think this is going to get actioned anytime soon, given our feedback above. Still a valueable discussion to have, and clarifications for others who might have the same idea.
