### ISSUE TITLE
Add overview of Campaigns feature to "No campaigns created yet" screen

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-campaign-admin#20]
# Acceptance Criteria

 * Each user will see an introduction in the campaigns section
 * The introduction always shows when first entering the campaign section - regardless of whether campaigns have been added or not (so each user gets a chance to learn about this section, not just the first one)
 * The introduction contains text, images and links
 * The content can be based on code (not database), but needs to be translatable
 * The introduction can be closed, and that choice is remembered per user (use localStorage, so it's per computer - don't need to go as far as column in the database)
 * The introduction can be opened again through a "help" icon trigger

# Excludes

 * Animations
 * Show introduction in a modal overlay (can be full width for now)

# Notes

 * Needs to work on small screen sizes
 * Should gracefully adapt to varying content lengths and image sizes
 * Should be reusable for other (React-based) sections
 * User choice should be persisted in local storage, avoid bloating the cookie string any further (it's sent with every HTTP request)

## Pull requests 
- [x] https://github.com/silverstripe/silverstripe-admin/pull/333
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/72

# Original Ticket Content

Instead of a big empty screen:

![](http://spdr.me/PeUSxt+)

How about adding a nice overview of the new Campaigns feature, with some screenshots to tell CMS users what it can do, making them more likely to make use of it?

Or, perhaps at least a link to the Campaigns user documention? 

**Assest:**
![campaigns-intro](https://user-images.githubusercontent.com/8085295/32078214-9fe80e68-bb02-11e7-98c2-3630fe574198.png)

**Comment by dhensby** [comment]
I think that's a good idea, but someone will need to take ownership of it...

**Comment by chillu** [comment]
@newleeland In the short term, can you please come up with some friendly wording that describes what a campaign is, instead of just the "No campaigns created yet". For now, I'm removing this from the milestone - it's an easy addition, but also a distraction.

**Comment by newleeland** [comment]
## Potential Prototype
https://invis.io/JMDCPH6KZ#/251980796_Campaign_-_Introduction_Modal_Copy

**Comment by chillu** [comment]
I think a single-page welcome screen is kind of pointless - you can just embed it into the layout then. Overall, I think "welcome" modals for new features can be helpful, if they have step-by-step screens. But that's a wider discussion.

Persistence of "what's this section" information doesn't feel like it should be in an "info" button. If somebody in your organisation has already created a campaign, and you're coming in as a newcomer to the CMS, you should look through the userhelp first and foremost. We could discuss creating more direct pointers to userhelp from specific sections, or embedding userhelp in modals. I'll leave that up to you for now.

In the short term, I think a simple design embedded in the "empty screen" is fine, no modals please.

**Comment by flamerohr** [comment]
@newleeland becareful with the use of animations, "fading and shrinking in to the `i` icon" is far more complex than just closing with a fade animation. Animation complexity has potential to grow exponentially with complexity, particularly when no team member has worked with html/css animations that extensively.

I'd suggest the info content be on a whole new page rather than modal, to me modals are justified for "actions which require a new screen/interface but you want to stay on the current screen"

I like the imagery, maybe the description could have more detail, maybe that could go through a peer review process as well.

**Comment by newleeland** [comment]
@chillu 
The reason we'll want an introductory screen in a separate modal is that if the when the first user of campaigns creates a campaign, this introductory screen would be replaced with a listing. Meaning the next users will not be guaranteed to be introduced to campaigns. Generally, its a better experience, when the user doesn't have to front-load information (first going to userhelp and learning about campaigns), but rather informative help text in placed context to their scenario.

We can peel back the UX a little have the message just show when there are no campaign listings. But a user is able to click a help button and view this message after campaign listings are created. Would this be a viable option
https://invis.io/JMDCPH6KZ#/251980796_Campaign_-_Introduction_Modal_Copy

**Comment by chillu** [comment]
> Generally, its a better experience, when the user doesn't have to front-load information (first going to userhelp and learning about campaigns), but rather informative help text in placed context to their scenario.

That's true, but it'll be quite a lot of effort in the CMS UX to make this apply consistently. I'm not sure we can afford to maintain extensive context help if we're already struggling to maintain the user docs that exist. Users will have many more questions about the operation of any given feature than a two sentence introduction screen. That questionmark will only serve users that come to a section after somebody else has entered info there already, but not users who generally want to learn more about the features. And that's what userhelp is for. We can discuss embedded userhelp into an overlay on the CMS with deep links into the correct section, rather than just linking off to a separate website. But I stand unconvinced that starting to apply specialised context sensitive help in the CMS is a good idea. /cc @clarkepaul

**Comment by clarkepaul** [comment]
@chillu I disagree with you on this one. Campaigns is a very abstract concept and could be used in the wrong way if the user didn't understand it correctly. This sort of in-page help isn't as important in the files area as the concept is a standard in most CMS's (but even then we should have some context as to what files are supported etc).

We've done testing in the past to see if people use the CMS Help and nearly everyone I asked said they didn't even know that existed, saying they only use the top few admin areas and don't bother to even know whats in the rest (this is a side issue that the help area isn't as noticeable as it should be). 

The text within this introduction screen isn't something that is likely to need maintaining as it would for actual documentation. There needs to some sort of marketing to inform and entice people to know about the section otherwise it won't be used. You're not really selling a car unless you advertise it, and likewise with this section, if you don't give it some promotion it could be something that doesn't get used because people are scared to use it.

The main point I'm getting to is that people don't use Help, and sections of the CMS should either be intuitive enough to use or provide some clues as to how the section is used, and I think this is the perfect scenario to introduce such a pattern.

**Comment by chillu** [comment]
userhelp.silverstripe.org had 22k users with 110k page views in the last 12 months.

I agree that the campaigns section needs introduction more urgently than other sections, and visible for every user (not just the first one to create a campaign). That being said, there's other features in the CMS which qualify for this level of introduction. And deep linking into userhelp would universally raise the profile of that existing learning resource. 

So if we're introducing new design elements (question mark), they should be universally applicable as a pattern. Once users see it in one place, they'll likely expect it for other locations as well. I'm not disagreeing with you per se, but would like to see a vision for how this single use case becomes a design pattern used across the CMS. Maybe there's a difference between "section-wide" help links (e.g. "assets" section) and "feature specific" help links (e.g. on a "userforms" page)? Not all sections will have an "add" button to put a question mark next to it - would users find it if it moves around?

For now, I'm happy to have the "empty screen" help implemented. For the question mark, I want to ensure the pattern "scales" to other sections and use cases.

**Comment by chillu** [comment]
Also, this design is quite different from the "getting started" screen already present in a new campaign:

![image](https://user-images.githubusercontent.com/111025/30667240-053527fc-9eab-11e7-88ef-89e4d763b0af.png)

**Comment by chillu** [comment]
Discussed with Paul and Jared, he'll work on making the two screen designs more consistent, and reduce the icon size. Can be implemented as-is otherwise. Moved the wider "context sensitive help" discussion into a separate card: https://github.com/silverstripe/silverstripe-admin/issues/270

**Comment by newleeland** [comment]
![screen shot 2017-09-22 at 12 52 42 pm](https://user-images.githubusercontent.com/8085295/30724877-002a670a-9f95-11e7-84c7-452550f514cb.png)

To make the imagery to look consistent, the "getting started" imagery would be easier to change to the more vector graphic. How's that sound to you @clarkepaul?

**Comment by newleeland** [comment]
Potential design

**Comment by newleeland** [comment]
**Potential Design**
https://invis.io/JMDCPH6KZ#/251980796_Campaign_-_Introduction_Modal_Copy

**Comment by newleeland** [comment]
After speaking with @flamerohr.
At the moment, userhelp.silverstripe.org/en/4.0/ is still in work in progress, hence all links and "Call to action" button are hidden so that once 4.0 is added to user, we turn on the Call to action button for the campaigns area if need be.
